name: Build & Upload Artifacts

on:
  push:
    branches: ['main', 'test']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Create virtual environment & Build Artifact on Unix
        if: runner.os != 'Windows'
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install .
          ls -la
          build

      - name: Create virtual environment & Build Artifact on Windows
        if: runner.os == 'Windows'
        run: |
          python -m venv .venv
          .venv\Scripts\activate
          pip install .
          build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MHGU_MHXX_Save_Converter_Script_${{ runner.os }}
          path: dist/**
          retention-days: 2
          compression-level: 9
          include-hidden-files: true
