name: Build and Package

on:
  push:
    branches: ["test"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Create and activate virtual environment on Unix
        if: runner.os != 'Windows'
        run: |
          python -m venv .venv
          source .venv/bin/activate
          
      - name: Create and activate virtual environment on Windows
        if: runner.os == 'Windows'
        run: |
          python -m venv .venv
          .venv\Scripts\activate
          
      - name: Build artifacts
        run: |
          pip install .
          build

      - name: Compress artifacts on Unix
        if: runner.os != 'Windows'
        run: |
            zip -r MHGU_MHXX_Save_Converter_Script_${{ runner.os }}.zip ./dist/*
      
      - name: Compress artifacts on Windows
        if: runner.os == 'Windows'
        run: |
          7z a MHGU_MHXX_Save_Converter_Script_${{ runner.os }}.zip ./dist/*

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MHGU_MHXX_Save_Converter_Script_${{ runner.os }}
          path: MHGU_MHXX_Save_Converter_Script_${{ runner.os }}.zip
          
  download:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        path: MHGU_MHXX_Save_Converter_Script
        pattern: MHGU_MHXX_Save_Converter_Script_*
        merge-multiple: true
